#!/usr/bin/perl
use FindBin qw($Bin);
use Cwd qw(abs_path);
$fq1=shift;
$fq2=shift;
$dirname=shift;
@out=split /\//,$fq1;
@out2=split /\//,$fq2;
@name=split /_/,$out[-1];
@name2=split /_/,$out2[-1];
@trim_name=split /\./,$out[-1];
@trim_name2= split /\./,$out2[-1];
$dir=abs_path($dirname);
`mkdir -p $dir/$name[0]/Shell`;
open F, ">$dir/$name[0]/Shell/$name[0]\_filter.sh";
print F "#!/bin/bash\n#SBATCH -N 1 -c 4\n";
print F "trim_galore --quality 20 --phred33 --stringency 3 --length 30 -o $dir/$name[0] --paired $fq1 $fq2\n";
print F "gunzip $dir/$name[0]/$trim_name[0]\_val_1.fq.gz $dir/$name[0]/$trim_name2[0]\_val_2.fq.gz\n";
print F"echo \"$dir/$name[0]/$trim_name[0]\_val_1.fq\n$dir/$name[0]/$trim_name2[0]\_val_2.fq\" > $dir/$name[0]/$name[0].list\n";
print F "fastuniq -i $dir/$name[0]/$name[0].list -o $dir/$name[0]/$name[0]\.1.fq -p $dir/$name[0]/$name[0]\.2.fq\n";
print F "seqtk trimfq -e 10 $dir/$name[0]/$name[0]\.1.fq > $dir/$name[0]/$name[0]\.1.cut.fq\nseqtk trimfq -b 10 $dir/$name[0]/$name[0]\.2.fq > $dir/$name[0]/$name[0]\.2.cut.fq\n";
print F "bowtie -S --rf -p 10 /home/weiqi/project/00.DATABASE/GRmm38/mm_rRNADatabase/mm_rRNA -1 $dir/$name[0]/$name[0]\.1.cut.fq -2 $dir/$name[0]/$name[0]\.2.cut.fq --un $dir/$name[0]/$name[0]\_rmrRNA.fq -S $dir/$name[0]/$name[0].rRNA.sam 2>$dir/$name[0]/$name[0].rRNA.rate.txt\n";
print F "rm $dir/$name[0]/$name[0].rRNA.sam\n";
print F "hisat2 -p 10 -I 0 -X 1000 --ma 0 --mp 4,2 --score-min L,0,-0.3 --rna-strandness RF --no-softclip --max-intronlen 4000 --dta-cufflinks --no-mixed --no-discordant --no-unal -x /home/weiqi/project/01.weiqi/20200929_inosine/process/index/GRCm38.p6 -1 $dir/$name[0]/$name[0]\_rmrRNA_1.fq -2 $dir/$name[0]/$name[0]\_rmrRNA_2.fq -S $dir/$name[0]/$name[0].sam 2>$dir/$name[0]/$name[0].mapping_rate.txt\n";
print F "samtools view -@ 16 -bS $dir/$name[0]/$name[0].sam | samtools sort -@ 16 -m 1000M -o $dir/$name[0]/$name[0].sorted.bam -T $dir/$name[0]/$name[0].tmp\n";
print F "samtools index -@ 16 $dir/$name[0]/$name[0].sorted.bam\n";
#print F "bamtools filter -in $dir/$name[0]/$name[0].sorted.bam -out $dir/$name[0]/$name[0].sorted.filter.bam -isPrimaryAlignment true -isProperPair true -isMapped true -mapQuality '>1'\n";
#print F "samtools index -@ 16 $dir/$name[0]/$name[0].sorted.filter.bam\n";
print F "rm $dir/$name[0]/$name[0].sam $dir/$name[0]/$name[0]*.fq\n";
close F;
